### ISSUE TITLE
Add a badge to ACR showing e10s status

### ISSUE THREAD

**Issue by andymckay** [mozilla/addon-compatibility-reporter#27]
Basically, when you are testing its easy to forget if you are in e10s mode or not. Its also hard to check. Let's make it easy and stick a badge that clearly says so before the user sends in their reports they are sure they are doing it right.

Somewhere in here?

![screenshot 2016-07-20 08 02 42](https://cloud.githubusercontent.com/assets/74699/16991423/66acf818-4e50-11e6-8f3b-815f2d2c9ddc.png)

And here?

![screenshot 2016-07-20 08 03 26](https://cloud.githubusercontent.com/assets/74699/16991460/823c9728-4e50-11e6-8e58-95866f29acd6.png)

Once we've got #25 done it should be easier.

Supports mozilla/addons#163

**Comment by wagnerand** [comment]
First part is done in #31. No sure whether the second part or #28 would be better.
