### ISSUE TITLE
Change GitHub project name to addons-compability-reporter

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addon-compatibility-reporter#40]
The ACR name obscures the intent of the project and I hear we can have folders longer than right characters now. 😉

**Comment by wagnerand** [comment]
Who can do that?

**Comment by tofumatt** [comment]
Actually, in fact, I cannot change it. I guess @andymckay has to do it.

Maybe he can give me/addon devs admin access to the repo?

**Comment by tofumatt** [comment]
I think I can, I just earmarked it here for now so I wouldn’t forget :-)

**Comment by tofumatt** [comment]
@jvillalobos any chance you have admin access and can do this (and grant me/addons devs admin access so we can administer the repo?)

**Comment by tofumatt** [comment]
Ping @brianking as well, sorry for all the noise!

**Comment by jvillalobos** [comment]
I gave you and Andreas admin access now.

**Comment by wagnerand** [comment]
Thank you! Renamed to `addon-compatibility-reporter`.
