### ISSUE TITLE
https:// is hardcoded, making local testing impossible

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addon-compatibility-reporter#41]
Because `olympia.dev` is only served over HTTP, testing ACR with local data is impossible (because it only asks for the AMO host name and not the protocol).

Easy solution is to check for a protocol in the host; if it's not found, assume HTTPS. This will allow developers to override the AMO host to `http://olympia.dev` for testing but remains backward compatible with the existing configs.

**Comment by wagnerand** [comment]
https://github.com/mozilla/ACR/pull/29#discussion_r72225975 heh :)
