### ISSUE TITLE
Make acr e10s compatible

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addon-compatibility-reporter#43]
We should test acr on e10s without shims, make changes if necessary, release a new version with the MPC flag set and ping Shell, preferably all before Aug 22nd so acr could be considered to be on the e10s 'allow list'. #onesentencegerman.

**Comment by wagnerand** [comment]
@tofumatt I tested in 51.0a1 and didn't find any issues. Just to be sure, could you give it a spin as well? Thanks!

**Comment by wagnerand** [comment]
Remember to disable the shims: `extensions.interposition.enabled`=> `false`.

**Comment by tofumatt** [comment]
I disabled the shims and it seems to work.
