### ISSUE TITLE
Make incompatible add-ons stand out more

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addon-compatibility-reporter#48]
That certain add-ons aren't multiprocess-compatible isn't well-highlighted in the list, we should add an icon or colour to signify it.

![unspecified](https://cloud.githubusercontent.com/assets/90871/17519166/aa2dad06-5e42-11e6-8705-aab40050d6f9.png)

**Comment by tofumatt** [comment]
Actually, the change to add links to multiprocess info (#34) makes things stand out a bit more. I'd say this is covered, what do you think @andymckay?

<img width="416" alt="screenshot 2016-08-09 18 21 59" src="https://cloud.githubusercontent.com/assets/90871/17526227/48aaff90-5e5e-11e6-8a40-371a96c21e74.png">

**Comment by andymckay** [comment]
Looks good lets give it a try. Thanks.

**Comment by grahamperrin** [comment]
[make incompatible add-ons outstanding in the list at about:addons · Issue #89 · mozilla/addon-compatibility-reporter](https://github.com/mozilla/addon-compatibility-reporter/issues/89)
