### ISSUE TITLE
Ignore themes

### ISSUE THREAD

**Issue by andymckay** [mozilla/addon-compatibility-reporter#63]
We don't need to worry about themes and e10s, although I'm never quite sure what heavy weight themes can do.

Should we not worry about showing their e10s status in ACR?

**Comment by cpeterso** [comment]
STR:
1. Open Add-ons Manager's Appearance tab.
2. Enable a different theme, e.g. Developer Edition.
3. Re-enable your original theme, e.g. Default.

RESULT:
Firefox's Default and Developer Edition themes are listed as not compatible. When you enable or disable a theme, the "Not compatible with multiprocess" warning appears.

**Comment by jvillalobos** [comment]
Yes, we shouldn't show ACR status for anything other than extensions.

**Comment by wagnerand** [comment]
We normally ignore everything except extensions. Seems like there is an issue when the enabled/disabled status of a non-extension changes.
