### ISSUE TITLE
ACR not working on FF 52 (Nightly) in Private Browsing Window

### ISSUE THREAD

**Issue by hwine** [mozilla/addon-compatibility-reporter#69]
I've noticed a number of issues with FF 52 (Mac) and extensions not working correctly. I finally had time to report them using ACR, and discovered it does not work either!

Even with ACR enabled, I get neither the "report issue" button in the extensions screen, nor the "jigsaw puzzle" icon in the footer.

![screen shot 2016-11-01 at 09 13 37](https://cloud.githubusercontent.com/assets/132412/19897011/90c4cfbc-a013-11e6-8eff-be0b027c9848.png)

**Comment by yfdyh000** [comment]
Work for me in 52.0a1 (2016-11-01) (32-bit) on Win10 x64.

Ctrl+Shift+J to check errors.

**Comment by hwine** [comment]
My bad -- it does not work when "About Addons" is opened in a private browsing window. Works fine in normal window. No idea if that is intended behavior or not.

**Comment by hwine** [comment]
Okay, ACR also does not work in FF 49 in a private browsing window, so assuming this is intended behavior. (Also makes me wonder if it ever makes sense to open about:addons in private browsing mode.)

**Comment by wagnerand** [comment]
I am not super familiar with that part of the code but it looks like as this is intended.
