### ISSUE TITLE
Rework as webextension?

### ISSUE THREAD

**Issue by hwine** [mozilla/addon-compatibility-reporter#81]
We're getting closer to the time when only webextensions will be allowed. This extension is still "legacy".

Is the intention to port this extension to a webextension? Or let it die with other legacy extensions?

**Comment by wagnerand** [comment]
With a clearly defined and stable API, I don't think we won't need this past 57.

**Comment by wagnerand** [comment]
We are also going to improve ways for users to report an add-on, for whatever reason.
