### ISSUE TITLE
No way to use addon?

### ISSUE THREAD

**Issue by AnAwesomeGit** [mozilla/addon-compatibility-reporter#82]
Hi,

I am running:

Release 16.04.2 LTS (Xenial Xerus) 64-bit
Kernel Linux 4.4.0-79-generic x86_64
MATE 1.12.1
and 
Firefox 54.0 (64 bit)

I installed ACR it gave me no errors but also no (compatibility) button or option in about:addons.
I don't know what is going wrong...
If you need any info just ask.

thx

![screenshot at 2017-06-19 14 20 38](https://user-images.githubusercontent.com/29543376/27284906-eee67c48-54fa-11e7-9e67-14dc9e5be5d5.png)

**Comment by wagnerand** [comment]
Hello!

Is this a private browsing window?
Can you check the browser console for any errors, please?

**Comment by AnAwesomeGit** [comment]
Hi!

Thanks for helping. 
No, it's not a private window.
This is all from console:

" NS_ERROR_DOM_BAD_URI: Component returned failure code: 0x805303f4 [nsIStreamListener.onStartRequest]  WebRequest.jsm:340 "

**Comment by wagnerand** [comment]
Thanks! Hm, that error doesn't seem related. Can you go to about:support, click on "Copy raw data to clipboard" and paste it here?

**Comment by AnAwesomeGit** [comment]
Here it is :)
{
  "application": {
    "name": "Firefox",
    "osVersion": "Linux 4.4.0-79-generic",
    "version": "54.0",
    "buildID": "20170612122310",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0",
    "safeMode": false,
    "supportURL": "https://support.mozilla.org/1/firefox/54.0/Linux/en-US/",
    "numTotalWindows": 1,
    "numRemoteWindows": 0,
    "remoteAutoStart": false,
    "autoStartStatus": 7,
    "keyGoogleFound": true,
    "keyMozillaFound": false
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "browser.cache.frecency_experiment": 1,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.disk.smart_size.enabled": false,
    "browser.cache.disk.smart_size.use_old_max": false,
    "browser.cache.disk.capacity": 0,
    "browser.cache.disk.filesystem_reported": 1,
    "browser.download.importedFromSqlite": true,
    "browser.places.importBookmarksHTML": false,
    "browser.places.smartBookmarksVersion": 8,
    "browser.privatebrowsing.autostart": true,
    "browser.search.update": false,
    "browser.sessionstore.upgradeBackup.latestBuildID": "20150922225347",
    "browser.startup.homepage": "https://start.duckduckgo.com",
    "browser.startup.homepage_override.buildID": "20170612122310",
    "browser.startup.homepage_override.mstone": "54.0",
    "browser.tabs.warnOnClose": false,
    "browser.tabs.remote.autostart.2": true,
    "browser.urlbar.suggest.history": false,
    "browser.urlbar.suggest.openpage": false,
    "dom.apps.reset-permissions": true,
    "dom.mozApps.used": true,
    "extensions.lastAppVersion": "54.0",
    "font.internaluseonly.changed": true,
    "gfx.crash-guard.glcontext.driverVersion": "4.5.0 NVIDIA 352.79",
    "gfx.crash-guard.glcontext.deviceID": "GeForce GT 610/PCIe/SSE2",
    "gfx.crash-guard.glcontext.appVersion": "45.4.0",
    "gfx.crash-guard.status.glcontext": 2,
    "media.gmp-manager.buildID": "20170612122310",
    "media.gmp.storage.version.observed": 1,
    "media.webrtc.debug.aec_log_dir": "/tmp",
    "media.webrtc.debug.log_file": "/tmp/WebRTC.log",
    "media.gmp-gmpopenh264.lastUpdate": 1476096514,
    "media.gmp-gmpopenh264.version": "1.6",
    "media.gmp-gmpopenh264.abi": "x86_64-gcc3",
    "media.gmp-manager.lastCheck": 1497797301,
    "network.cookie.prefsMigrated": true,
    "network.predictor.cleaned-up": true,
    "places.history.expiration.transient_current_max_pages": 57389,
    "places.database.lastMaintenance": 1497612913,
    "plugin.importedState": true,
    "plugin.disable_full_page_plugin_for_types": "application/pdf",
    "print.print_resolution_name": "default",
    "print.print_to_file": false,
    "print.print_page_delay": 50,
    "print.print_orientation": 0,
    "print.print_colorspace": "default",
    "print.print_paper_name": "iso_a4",
    "print.print_unwriteable_margin_right": 25,
    "print.print_paper_height": "297,00",
    "print.print_scaling": "  1,00",
    "print.print_unwriteable_margin_left": 25,
    "print.print_unwriteable_margin_bottom": 56,
    "print.print_duplex": 0,
    "print.print_margin_right": "0.5",
    "print.print_oddpages": true,
    "print.print_bgcolor": false,
    "print.print_paper_width": "210,00",
    "print.print_bgimages": false,
    "print.print_downloadfonts": false,
    "print.print_paper_size_type": 1,
    "print.print_shrink_to_fit": true,
    "print.print_margin_left": "0.5",
    "print.print_plex_name": "default",
    "print.print_margin_top": "0.5",
    "print.print_unwriteable_margin_top": 25,
    "print.print_margin_bottom": "0.5",
    "print.print_in_color": true,
    "print.print_paper_data": 0,
    "print.print_paper_size_unit": 1,
    "print.print_evenpages": true,
    "print.print_resolution": 1200,
    "privacy.cpd.siteSettings": true,
    "privacy.sanitize.migrateFx3Prefs": true,
    "privacy.item.extensions-privacyplus": false,
    "privacy.cpd.offlineApps": true,
    "services.sync.declinedEngines": "",
    "storage.vacuum.last.places.sqlite": 1495467087,
    "storage.vacuum.last.index": 1
  },
  "lockedPreferences": {},
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.14",
      "version": "4.14"
    },
    "NSS": {
      "minVersion": "3.30.2",
      "version": "3.30.2"
    },
    "NSSUTIL": {
      "minVersion": "3.30.2",
      "version": "3.30.2"
    },
    "NSSSSL": {
      "minVersion": "3.30.2",
      "version": "3.30.2"
    },
    "NSSSMIME": {
      "minVersion": "3.30.2",
      "version": "3.30.2"
    }
  },
  "userJS": {
    "exists": false
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "sandbox": {
    "hasSeccompBPF": true,
    "hasSeccompTSync": true,
    "hasPrivilegedUserNamespaces": true,
    "hasUserNamespaces": true,
    "canSandboxContent": true,
    "canSandboxMedia": true,
    "syscallLog": [],
    "contentSandboxLevel": 2
  },
  "experiments": [],
  "extensions": [
    {
      "name": "Add-on Compatibility Reporter",
      "version": "2.2.3",
      "isActive": true,
      "id": "compatibility@addons.mozilla.org"
    },
    {
      "name": "Application Update Service Helper",
      "version": "2.0",
      "isActive": true,
      "id": "aushelper@mozilla.org"
    },
    {
      "name": "Disconnect",
      "version": "5.18.21",
      "isActive": true,
      "id": "2.0@disconnect.me"
    },
    {
      "name": "Firefox Screenshots",
      "version": "6.6.0",
      "isActive": true,
      "id": "screenshots@mozilla.org"
    },
    {
      "name": "Follow-on Search Telemetry",
      "version": "0.8.0",
      "isActive": true,
      "id": "followonsearch@mozilla.com"
    },
    {
      "name": "Ghostery",
      "version": "7.2.2",
      "isActive": true,
      "id": "firefox@ghostery.com"
    },
    {
      "name": "Multi-process staged rollout",
      "version": "1.50",
      "isActive": true,
      "id": "e10srollout@mozilla.org"
    },
    {
      "name": "Pocket",
      "version": "1.0.5",
      "isActive": true,
      "id": "firefox@getpocket.com"
    },
    {
      "name": "Ubuntu Modifications",
      "version": "3.2",
      "isActive": true,
      "id": "ubufox@ubuntu.com"
    },
    {
      "name": "View Cookies",
      "version": "1.13",
      "isActive": true,
      "id": "{8F6A6FD9-0619-459f-B9D0-81DE065D4E21}"
    },
    {
      "name": "Web Compat",
      "version": "1.1",
      "isActive": true,
      "id": "webcompat@mozilla.org"
    },
    {
      "name": "BrowserProtect",
      "version": "1.1.3.1-signed",
      "isActive": false,
      "id": "browserprotect@browserprotect.com"
    },
    {
      "name": "Cookies Manager+",
      "version": "1.13.3",
      "isActive": false,
      "id": "{bb6bc1bb-f824-4702-90cd-35e2fb24f25d}"
    },
    {
      "name": "Download YouTube Videos as MP4",
      "version": "1.8.10",
      "isActive": false,
      "id": "{b9bfaf1c-a63f-47cd-8b9a-29526ced9060}"
    },
    {
      "name": "Flash and Video Download",
      "version": "2.06",
      "isActive": false,
      "id": "{bee6eb20-01e0-ebd1-da83-080329fb9a3a}"
    },
    {
      "name": "Flashblock",
      "version": "1.5.20",
      "isActive": false,
      "id": "{3d7eb24f-2740-49df-8937-200b1cc08f8a}"
    },
    {
      "name": "GNOME Shell integration",
      "version": "8.2.1",
      "isActive": false,
      "id": "chrome-gnome-shell@gnome.org"
    },
    {
      "name": "GNU LibreJS",
      "version": "6.0.13",
      "isActive": false,
      "id": "jid1-KtlZuoiikVfFew@jetpack"
    },
    {
      "name": "Google Translator for Firefox",
      "version": "2.1.0.5.3",
      "isActive": false,
      "id": "translator@zoli.bod"
    },
    {
      "name": "Netcraft Anti-Phishing Toolbar",
      "version": "1.10.3",
      "isActive": false,
      "id": "{0e10f3d7-07f6-4f12-97b9-9b27e07139a5}"
    },
    {
      "name": "Privacy Plus",
      "version": "1.0.2",
      "isActive": false,
      "id": "mozilla@z33.ch"
    },
    {
      "name": "Random Agent Spoofer",
      "version": "0.9.5.6",
      "isActive": false,
      "id": "jid1-AVgCeF1zoVzMjA@jetpack"
    },
    {
      "name": "Self-Destructing Cookies",
      "version": "0.4.12",
      "isActive": false,
      "id": "jid0-9XfBwUWnvPx4wWsfBWMCm4Jj69E@jetpack"
    },
    {
      "name": "Translate This!",
      "version": "3.5.1",
      "isActive": false,
      "id": "jid0-k75TfRGfOXPHfEZmJ9cKu5eCgLc@jetpack"
    },
    {
      "name": "YouTube Video and Audio Downloader",
      "version": "0.5.9",
      "isActive": false,
      "id": "feca4b87-3be4-43da-a1b1-137c24220968@jetpack"
    }
  ],
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 0,
    "windowLayerManagerType": "Basic",
    "windowLayerManagerRemote": true,
    "currentAudioBackend": "pulse",
    "numAcceleratedWindowsMessage": [
      ""
    ],
    "adapterDescription": "nouveau -- Gallium 0.4 on NVD9",
    "adapterVendorID": "nouveau",
    "adapterDeviceID": "Gallium 0.4 on NVD9",
    "adapterRAM": "",
    "adapterDrivers": "",
    "driverVersion": "3.0 Mesa 12.0.6",
    "driverDate": "",
    "webgl1Renderer": "nouveau -- Gallium 0.4 on NVD9",
    "webgl1Version": "3.0 Mesa 12.0.6",
    "webgl1DriverExtensions": "GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_depth_bounds_test GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_NV_vdpau_interop GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_shader_draw_parameters GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_EXT_polygon_offset_clamp GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_shader_atomic_counter_ops ",
    "webgl1Extensions": "ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_frag_depth EXT_sRGB EXT_shader_texture_lod EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug_get OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_etc WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc MOZ_WEBGL_depth_texture",
    "webgl1WSIInfo": "GLX 1.4\nGLX_VENDOR(client): Mesa Project and SGI\nGLX_VENDOR(server): SGI\nExtensions: GLX_ARB_create_context GLX_ARB_create_context_profile GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_import_context GLX_EXT_visual_info GLX_EXT_visual_rating GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_EXT_texture_from_pixmap GLX_INTEL_swap_event ",
    "webgl2Renderer": "nouveau -- Gallium 0.4 on NVD9",
    "webgl2Version": "4.3 (Core Profile) Mesa 12.0.6",
    "webgl2DriverExtensions": "GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_performance_monitor GL_AMD_shader_trinary_minmax GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_occlusion_query2 GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_sprite GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding GL_ARB_shader_draw_parameters GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ATI_blend_equation_separate GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_shader_integer_mix GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_IBM_multimode_draw_arrays GL_KHR_context_flush_control GL_KHR_debug GL_KHR_robust_buffer_access_behavior GL_MESA_pack_invert GL_MESA_texture_signed_rgba GL_NV_conditional_render GL_NV_depth_clamp GL_NV_packed_depth_stencil GL_NV_texture_barrier GL_NV_vdpau_interop GL_OES_EGL_image GL_OES_read_format GL_S3_s3tc",
    "webgl2Extensions": "EXT_color_buffer_float EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug_get OES_texture_float_linear WEBGL_compressed_texture_etc WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc",
    "webgl2WSIInfo": "GLX 1.4\nGLX_VENDOR(client): Mesa Project and SGI\nGLX_VENDOR(server): SGI\nExtensions: GLX_ARB_create_context GLX_ARB_create_context_profile GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_import_context GLX_EXT_visual_info GLX_EXT_visual_rating GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_EXT_texture_from_pixmap GLX_INTEL_swap_event ",
    "info": {
      "AzureCanvasBackend": "skia",
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "skia",
      "AzureCanvasAccelerated": 0,
      "CairoUseXRender": 0
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "blocked",
          "log": [
            {
              "type": "default",
              "status": "blocked",
              "message": "Acceleration blocked by platform"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "unavailable",
              "message": "Hardware compositing is disabled"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "available"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "Build doesn't include WebRender"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  }
}

**Comment by wagnerand** [comment]
Hm, so "browser.privatebrowsing.autostart" is set to `true` which means all windows are private browsing windows...the add-on does not work in private browsing windows.

**Comment by AnAwesomeGit** [comment]
thanks! i dont remember setting that as an option, but i will set it right this time :D 

thanks again!

**Comment by AnAwesomeGit** [comment]
And of course it works...

thank you so much!

**Comment by wagnerand** [comment]
Glad we got it sorted out!

**Comment by AnAwesomeGit** [comment]
Yes, me too. Now to figure out a way to really test addons while forcing multiprocess... I'd like to keep my trusted addons :)
