### ISSUE TITLE
Firefox 55 - missing text

### ISSUE THREAD

**Issue by andibing** [mozilla/addon-compatibility-reporter#83]
The view in Addons Manager "Compatible with multiprocess" or "Not compatible with multiprocess" does not appear in Firefox 55.

Tested so far in Betas 1, 2 and 3. On Ubuntu 17.04 and Windows 8

A>

Add-on Compatibility Reporter : v 2.2.3
Firefox : 55beta3

**Comment by wagnerand** [comment]
Are you in a private browsing window?
Can you please check the error console for any errors?
Can you please provide the log of `about:support`?

**Comment by wagnerand** [comment]
Ah, I found it.

Fixed in 31efe92fdef9e4fe7aa1edf5f64220cab2518c45.

**Comment by wagnerand** [comment]
Thank you for the report!

**Comment by andibing** [comment]
No probs.. Thanks for the quick fix :-)

Re-tested v 2.2.4 of the plugin on 
  FF55b3/Windows 7SP1
  FF55b3/Windows 8
...and so far all appears well.

Andi
