### ISSUE TITLE
Add-ons Manager doesn't display correctly after restart

### ISSUE THREAD

**Issue by bottleblue** [mozilla/addon-compatibility-reporter#84]
I noticed a quirk with this addon.  When my firefox restarts it show the tabs from the last session. If I have 
Add-ons Manager in an unfocused tab when firefox restarts and then I open it it won't load Add-ons Manager. It shows a loading animation forever. If I reload the tab then I can see AOM but it displays all the categories (Extensions, Appearance, Plugins, etc.) on one page instead of individually and clicking on a category doesn't change anything. I have to close the tab and reopen AOM to have it display correctly. This was tested on Firefox 54.

**Comment by wagnerand** [comment]
Thanks for the report.

This sounds like an AOM bug.

**Comment by bottleblue** [comment]
Did this happen to you too?

**Comment by wagnerand** [comment]
No. Can you reproduce this in a new profile or in safe-mode?

**Comment by bottleblue** [comment]
Yes I tried it on a new profile and the same thing happens with it trying to load forever although it doesn't show all the categories on one page when I reload the tab. This whole thing is not a huge problem since I can just disable this addon when I'm not installing new addons. But I thought I should report it anyways.

**Comment by wagnerand** [comment]
Could you maybe provide a screencast that shows what you are doing and what happens, please?

**Comment by bottleblue** [comment]
Where do I upload the video to?

**Comment by wagnerand** [comment]
Any hosting site is fine, or you can upload it to github if the format is supported.

**Comment by bottleblue** [comment]
What hosting sites? How do I upload it on github? I'll try to do that but I don't have much experience in capturing video so I don't know if it'll be successful. Also in my original post I said reloading tab displays all the categories but I might have been mistaken. Reloading tab seems to fix the issue but it always sets the page to "Get Add-ons". Clicking on any category after I get the infinite reloading will display all categories at once. Anyways, I'll try to make a screencast if I can.

**Comment by wagnerand** [comment]
You can drag and drop the file into the comment text box in this issue.

**Comment by wagnerand** [comment]
We haven't heard back from you in a while, so I am closing this issue. Feel free to reopen after you provided the requested information.
Thank you.
