### ISSUE TITLE
Why is this a Legacy Add-on?

### ISSUE THREAD

**Issue by asjones987** [mozilla/addon-compatibility-reporter#87]
Very confused why a Mozilla published add-on would be listed as a Legacy Add-on and not a “Compatible with Firefox 57+” add-on. I am a big fan of Firefox, but this looks really embarrassing for Mozilla (I have supported Mozilla since the beginning, but this is bad). All of Mozilla's stuff should have been the first to be converted to any new standards. That would be part of a process to see if there were any issues.

**Comment by jvillalobos** [comment]
We haven't made a final decision on this, but it's likely we'll discontinue this add-on after Firefox 57. The WebExtensions API will still experience compatibility issues, but it will only be a small fraction of what is reported for legacy add-ons. So, it probably doesn't warrant the tooling that we currently use, this add-on included.

**Comment by grahamperrin** [comment]
Thanks, pending the decision please consider updating the description at https://addons.mozilla.org/firefox/addon/add-on-compatibility-reporter/ to avoid users of 57 e.g. https://addons.mozilla.org/firefox/addon/add-on-compatibility-reporter/reviews/907445/ being surprised by the incompatibility.

**Comment by davidhedlund** [comment]
@jvillalobos Is Add-on Compatibility Reporter a [hybrid WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions) yet?

**Comment by davidhedlund** [comment]
@jvillalobos Please answer here instead: https://github.com/mozilla/addon-compatibility-reporter/issues/88
