### ISSUE TITLE
WebExtension status to AMO page

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/addon-compatibility-reporter#88]
The [AMO](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/) page will place this tag once the add-on is a WebExtension:

> Compatible with Firefox 57+

Until then people will continue to ask for the WebExtension status in their AMO Reviews for this add-on, so can you please state on the AMO page if it is:
* not a hybrid WebExtension
* a [hybrid WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions).

Also, please mention if the current WebExtension API is to restricted for this add-on to become a full WebExtension.

**Comment by wagnerand** [comment]
You already mentioned it: The fact that the tag is not there means that the add-on is not a WebExtension. It doesn't matter whether the add-on is a hybrid WebExtension or not, both will stop working in 57.

**Comment by davidhedlund** [comment]
@wagnerand I respect your decision.
