### ISSUE TITLE
make incompatible add-ons outstanding in the list at about:addons

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addon-compatibility-reporter#89]
![2017-09-09 06 36 26](https://user-images.githubusercontent.com/192271/30239223-91035bec-954f-11e7-92b0-3ee8df0c4a59.png)

The blue of the circle around the **ℹ** stands out more (contrasted against the white background) than the yellow of the triangle around the exclamation mark. 

More generally: 

- the _compatible_ lines are superfluous, their presence does **not** make it easier to see, at a glance, what's compatible. 

Better (mocked up): 

![2017-09-09 mock up](https://user-images.githubusercontent.com/192271/30239235-fc1e5da0-954f-11e7-8750-eeb41422ba1e.png)

It might be even better to apply a yellow highlight to the relevant text, 

> Not compatible with multiprocess.

– but (please) don't make it as LARGE, LOUD AND SHOUTY as the 'LEGACY' alerts that are integral to Firefox 55. 

If not highlighted text, then maybe a different colour triangle, or a more contrasting border to the triangle, for the exclamation mark. 

Thanks

**Comment by grahamperrin** [comment]
I guess that attention to just a handful of lines, including <https://github.com/mozilla/addon-compatibility-reporter/blob/2bb1975d538d4f0dbdf09a838d38818be3d664df/data/reporter.js#L64> and <https://github.com/mozilla/addon-compatibility-reporter/blob/2bb1975d538d4f0dbdf09a838d38818be3d664df/data/reporter.js#L118> might be enough. 

(For myself I tried, but failed, to install a hacked copy of the extension.)

**Comment by wagnerand** [comment]
This add-on will stop working with Firefox 57 and we don't plan to make any more changes to it.
