### ISSUE TITLE
Desktop Messenger for Telegram™ doesn't match with No-Script

### ISSUE THREAD

**Issue by borzlav** [mozilla/addon-compatibility-reporter#91]
No-Script prevents clear displaying pop-ups from Telegram in the tab of Mozilla 56.0 (32 bits).
I just had to clear up No-Script

**Comment by wagnerand** [comment]
Thank you for the report.

This repository is about the development of the "Add-on compatibility reporter" add-on. For issues with other add-ons, please contact their developer directly.
